#pragma once
#include <array>
#include <cstdint>
#include <filesystem>
#include <string>

// P0-C-DEV (DISTRIBUTION-PHASE0.md): dev-mode credential stand-in for
// the proper credential store coming in P0-C1/C3.
//
// Reads <configPath>/inkternity_dev_keys.json at startup. The file
// format matches dev_mint_token.py --save-state output, so the same
// keypair/canvas tuple drives both the host (which verifies tokens)
// and the dev mint script (which produces them).
//
// Phase 1 (DISTRIBUTION-PHASE1.md §3) added Stellar strkey encoding
// for the app keypair + an optional BIP-39 mnemonic. The on-disk
// shape is now:
//
//   {
//     "member_secret": "S..." or hex,
//     "member_pub":    "G..." or hex,
//     "app_secret":    "S..." (strkey, 56 chars)  -- post-Phase 1
//                       or hex (128 chars)         -- legacy, auto-migrated
//     "app_pub":       "G..." (strkey, 56 chars)  -- post-Phase 1
//                       or hex (64 chars)          -- legacy, auto-migrated
//     "app_mnemonic":  "word1 word2 ... word12"   -- present for fresh
//                       Phase-1+ installs; absent for migrated installs
//                       (legacy random seeds had no mnemonic backing them)
//     "canvas_id":     "uuid"
//   }
//
// Inkternity reads only the public fields + canvas_id; the secrets
// live alongside purely so dev_mint_token.py can mint matching tokens
// without manual copy/paste.
//
// When loaded, World::start_hosting auto-populates the canvas's
// subscription fields from these values, so EVERY hosted canvas runs
// in subscriber-only mode and accepts dev-minted tokens. This is
// strictly a Phase-0 dev convenience — production replaces it with
// portal-issued credentials + a Publish-for-Subscribers UI that sets
// the canvas's fields explicitly.
//
// Absence of the file = vanilla collab mode (existing behavior).
class DevKeys {
    public:
        // Phase 1: ensure an app keypair exists at first run *in canonical
        // strkey form*. Behavior:
        //   - file absent or app_pub/app_secret missing → generate fresh
        //     (BIP-39 mnemonic → SEP-0005 derive → write G... + S... +
        //     mnemonic). User's seed is silently created — see the
        //     `feedback-crypto-averse-users` UX constraint for why
        //     there's no first-run modal.
        //   - file has hex-format pair (legacy Phase-0 alpha) → migrate
        //     in place: extract the existing 32-byte seed bytes, re-encode
        //     as G.../S..., rewrite the file. Share codes derived from
        //     these seed bytes (DISTRIBUTION-PHASE0.md §12.5) survive
        //     byte-for-byte. mnemonic stays empty (we never had one).
        //   - file has strkey-format pair → no-op.
        // Idempotent. Call BEFORE load(). Returns true iff the file was
        // newly written or migrated this call.
        bool ensure_app_keypair(const std::filesystem::path& configPath);

        // Returns true if the file existed and parsed cleanly. Logs
        // [USERINFO] on success/failure either way.
        bool load(const std::filesystem::path& configPath);

        bool is_loaded()                    const { return loaded; }
        const std::string& member_pubkey()  const { return memberPub; }

        // Stellar strkey form (G..., 56 chars) post-migration. May still
        // be raw hex if a stale on-disk file slipped through ensure_app_keypair.
        const std::string& app_pubkey()     const { return appPub; }

        // Stellar strkey form (S..., 56 chars) post-migration. May still
        // be raw hex (128 chars) if a stale file slipped through.
        // Consumers that need the *bytes* (for HMAC, signing, etc.)
        // should use app_seed_bytes() instead — that one is encoding-
        // agnostic and always populated when is_loaded() is true.
        const std::string& app_secret()     const { return appSecret; }

        // 12-word BIP-39 English mnemonic. Non-empty iff the keypair was
        // generated by Phase-1+ ensure_app_keypair from a mnemonic.
        // Empty for installs migrated from a hex random seed (no
        // mnemonic was ever associated with that seed). The Settings →
        // Export App Key popup uses this to decide whether to surface
        // the mnemonic block at all.
        const std::string& app_mnemonic()   const { return appMnemonic; }

        const std::string& canvas_id()      const { return canvasId; }

        // Raw 32-byte ed25519 seed — the universal HMAC key for the
        // CanvasShareId derivation (DISTRIBUTION-PHASE0.md §12.5) and
        // the input to ed25519 sign-keypair. Decoded from whatever
        // on-disk format `app_secret` happens to be. Always populated
        // when is_loaded() is true; zero-filled otherwise.
        const uint8_t* app_seed_bytes() const { return appSeedBytes.data(); }

    private:
        bool loaded = false;
        std::string memberPub;
        std::string appPub;
        std::string appSecret;
        std::string appMnemonic;
        std::string canvasId;
        std::array<uint8_t, 32> appSeedBytes{};
};
